using System;

namespace PreconIQAPI.DTOs
{
    /// <summary>
    /// DTO class to hold ProjectWindBODData information.
    /// </summary>
    public class ProjectWindBODDataDto
    {
        public int Id { get; set; }
        public string? OpportunityId { get; set; }
        public string? SourceLocation { get; set; }
        public DateTime? RunDate { get; set; }
        public string? ProjectName { get; set; }
        public string? Owner { get; set; }
        public string? Location { get; set; }
        public decimal? MwacMw { get; set; }
        public int? InterconnectVoltageKv { get; set; }
        public int? NumberOfTurbines { get; set; }
        public string? TurbineOem { get; set; }
        public string? TurbineModel { get; set; }
        public decimal? TurbineMw { get; set; }
        public int? TurbineHubHeightFt { get; set; }
        public int? TurbineRotorDiameterM { get; set; }
        public string? OwnerSuppliedEquipment { get; set; }
        public string? TurbineLocations { get; set; }
        public string? SubstationLocation { get; set; }
        public string? TransmissionRoute { get; set; }
        public string? AltaSurvey { get; set; }
        public string? LandControl { get; set; }
        public string? EnvironmentalConstraints { get; set; }
        public string? Geotech { get; set; }
        public string? TopoSurveySurfaceLidar { get; set; }
        public string? InterconnectAgreement { get; set; }
        public string? Ppa { get; set; }
        public string? Hydrology { get; set; }
        public string? WetlandDelineation { get; set; }
        public string? DesignVehicleComponentDelivery { get; set; }
        public string? AccessRoadDesign { get; set; }
        public string? PublicRoadNetworkHaulRoute { get; set; }
        public string? TempRoadXsection { get; set; }
        public string? PermRoadXsection { get; set; }
        public int? HorizCurveMinRadiusFt { get; set; }
        public int? AccessRoadsWidthFt { get; set; }
        public int? VerticalCurveRadiusFt { get; set; }
        public decimal? MaxLongitudinalGradientPct { get; set; }
        public decimal? CrossSlopeAccessRoadPct { get; set; }
        public decimal? CrossSlopeCranePathPct { get; set; }
        public int? TurbineCenterpinOffsetFt { get; set; }
        public string? TemporaryIntersections { get; set; }
        public int? StandardTempRadiusFt { get; set; }
        public string? BumpOutDimensions { get; set; }
        public int? BumpOutIntervalFt { get; set; }
        public int? CraneWalkWidthFt { get; set; }
        public string? CrossCountryCranePath { get; set; }
        public string? AccessRoadAggregateGradation { get; set; }
        public decimal? TurbineTempDisturbanceAc { get; set; }
        public string? TurbineTopOfPadSizeFt { get; set; }
        public string? TurbineTopOfPadShape { get; set; }
        public string? CranePadSizeFt { get; set; }
        public string? GravelRingDimensionFt { get; set; }
        public string? EgSurface { get; set; }
        public string? GradingType { get; set; }
        public int? AccessRoadEarthworkCy { get; set; }
        public int? WtgPadsEarthworkCy { get; set; }
        public int? TopsoilOrganicDepthIn { get; set; }
        public string? LowWaterCrossings { get; set; }
        public string? Culverts { get; set; }
        public string? ApproachCulverts { get; set; }
        public int? MinPipeDiameterIn { get; set; }
        public string? DesignStormTurbineFlooding { get; set; }
        public int? DisturbanceRoadsWidthFt { get; set; }
        public int? DisturbanceCraneWalkWidthFt { get; set; }
        public decimal? DisturbanceSiteAc { get; set; }
        public string? DisturbanceGradingLimits { get; set; }
        public int? DisturbanceUgCollectionWidthFt { get; set; }
        public string? CoordinateSystem { get; set; }
        public int? CollTopsoilStrippedDepthIn { get; set; }
        public int? CollTopsoilStrippedWidthPerCctFt { get; set; }
        public decimal? CollClearingAcres { get; set; }
        public string? CollCulturalAvoidances { get; set; }
        public string? CollEnvironmentalConstraints { get; set; }
        public string? CollPipelineCrossings { get; set; }
        public string? CollGprs { get; set; }
        public string? CollSwpppRequirements { get; set; }
        public string? TrenchInstallationMethod { get; set; }
        public string? CableInstallationMethod { get; set; }
        public string? MvCableOrientation { get; set; }
        public decimal? TrenchDepthFt { get; set; }
        public decimal? TrenchDepthToTopOfCablesFt { get; set; }
        public string? TrenchBedding { get; set; }
        public decimal? TrenchWidthFt { get; set; }
        public string? TrenchBackfillLayer1 { get; set; }
        public decimal? Layer1ScreenSizeIn { get; set; }
        public string? Layer1ScreeningMethod { get; set; }
        public string? Layer1CompactionMethod { get; set; }
        public string? TrenchBackfillLayer2 { get; set; }
        public decimal? Layer2ScreenSizeIn { get; set; }
        public string? Layer2ScreeningMethod { get; set; }
        public string? Layer2CompactionMethod { get; set; }
        public decimal? TrenchCompactionPctStdProctor { get; set; }
        public int? MaxLiftIn { get; set; }
        public string? CompactionTestingFrequency { get; set; }
        public decimal? AssumedRockPct { get; set; }
        public string? TerrainIssues { get; set; }
        public string? CarsoniteMarkers { get; set; }
        public string? MarkerBalls { get; set; }
        public decimal? NativeRho { get; set; }
        public decimal? DryRho { get; set; }
        public int? MaxMvCableSizeMcm { get; set; }
        public int? MaxLoadingAt90cAmp { get; set; }
        public int? MaxSegmentLengthWithTailsFt { get; set; }
        public int? TailLengthOneSideFt { get; set; }
        public int? MaxTurbinesPerFeeder { get; set; }
        public string? FeederCableSizeSpec { get; set; }
        public string? Grounding { get; set; }
        public string? Crossbonding { get; set; }
        public string? MidSpanGrounding { get; set; }
        public decimal? MvConductorScWithstandKa { get; set; }
        public decimal? ConcentricNeutralScWithstandKa { get; set; }
        public decimal? TrenchGroundScWithstandKa { get; set; }
        public decimal? MvCableVoltageKv { get; set; }
        public string? MvCableConductor { get; set; }
        public string? MvCableConductorShield { get; set; }
        public string? MvCableInsulation { get; set; }
        public string? MvCableInsulationShield { get; set; }
        public string? MvCableMetallicShield { get; set; }
        public string? MvCableJacket { get; set; }
        public int? MvCableMaxContTempC { get; set; }
        public int? MvCableEmergencyTempC { get; set; }
        public string? MvCableApprovedVendors { get; set; }
        public string? SingleModeFiber { get; set; }
        public string? Innerduct { get; set; }
        public string? InnerductPreloadedWithFiber { get; set; }
        public string? FiberApprovedVendors { get; set; }
        public decimal? BilKv { get; set; }
    }
}
