// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreconIQAPI.Data;

#nullable disable

namespace PreconIQAPI.Migrations
{
    [DbContext(typeof(PreconDbContext))]
    [Migration("20251119214114_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Precon")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PreconIQAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWon")
                        .HasColumnType("bit");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OpportunityLegalContractProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OpportunityName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OpportunityStageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Project", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BidAsCompany")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BidNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedFinalContractRevenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsParentOpportunity")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("MarginDollars")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MarginPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MarketSegment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Megawatts")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("OpportunityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ProjectCompletionDate")
                        .HasColumnType("date");

                    b.Property<int>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ProjectStartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RevenueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("SubstantialCompletionDate")
                        .HasColumnType("date");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMetaData", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectNormals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AvgHighTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgHighWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgLowTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgLowWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgRain")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgSnow")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<decimal?>("RecordAvgHighTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordAvgHighWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordAvgLowTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordAvgLowWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordHighAvgRain")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordHighAvgSnow")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordLowAvgRain")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordLowAvgSnow")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectNormals", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectWindData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expver")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<double>("U10")
                        .HasColumnType("float");

                    b.Property<double>("V10")
                        .HasColumnType("float");

                    b.Property<DateTime>("ValidTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWindData", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectMetaData", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "ParentProject")
                        .WithMany()
                        .HasForeignKey("ParentProjectId");

                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectNormals", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectWindData", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
