// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreconIQAPI.Data;

#nullable disable

namespace PreconIQAPI.Migrations
{
    [DbContext(typeof(PreconDbContext))]
    partial class PreconDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Precon")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PreconIQAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWon")
                        .HasColumnType("bit");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OpportunityLegalContractProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OpportunityName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OpportunityStageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Project", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BidAsCompany")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BidNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedFinalContractRevenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsParentOpportunity")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("MarginDollars")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MarginPercent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MarketSegment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Megawatts")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("OpportunityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ProjectCompletionDate")
                        .HasColumnType("date");

                    b.Property<int>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ProjectStartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RevenueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("SubstantialCompletionDate")
                        .HasColumnType("date");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMetaData", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectNormals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AvgHighTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgHighWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgLowTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgLowWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgRain")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("AvgSnow")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<decimal?>("RecordAvgHighTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordAvgHighWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordAvgLowTemp")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordAvgLowWind")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordHighAvgRain")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordHighAvgSnow")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordLowAvgRain")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("RecordLowAvgSnow")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectNormals", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectWindBODData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessRoadAggregateGradation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccessRoadDesign")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AccessRoadEarthworkCy")
                        .HasColumnType("int");

                    b.Property<int?>("AccessRoadsWidthFt")
                        .HasColumnType("int");

                    b.Property<string>("AltaSurvey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApproachCulverts")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AssumedRockPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("BilKv")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("BumpOutDimensions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BumpOutIntervalFt")
                        .HasColumnType("int");

                    b.Property<string>("CableInstallationMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CarsoniteMarkers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CollClearingAcres")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("CollCulturalAvoidances")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CollEnvironmentalConstraints")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CollGprs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CollPipelineCrossings")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CollSwpppRequirements")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CollTopsoilStrippedDepthIn")
                        .HasColumnType("int");

                    b.Property<int?>("CollTopsoilStrippedWidthPerCctFt")
                        .HasColumnType("int");

                    b.Property<string>("CompactionTestingFrequency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ConcentricNeutralScWithstandKa")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("CoordinateSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CranePadSizeFt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CraneWalkWidthFt")
                        .HasColumnType("int");

                    b.Property<string>("CrossCountryCranePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CrossSlopeAccessRoadPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CrossSlopeCranePathPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Crossbonding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Culverts")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DesignStormTurbineFlooding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DesignVehicleComponentDelivery")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DisturbanceCraneWalkWidthFt")
                        .HasColumnType("int");

                    b.Property<string>("DisturbanceGradingLimits")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DisturbanceRoadsWidthFt")
                        .HasColumnType("int");

                    b.Property<decimal?>("DisturbanceSiteAc")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("DisturbanceUgCollectionWidthFt")
                        .HasColumnType("int");

                    b.Property<decimal?>("DryRho")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("EgSurface")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EnvironmentalConstraints")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FeederCableSizeSpec")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FiberApprovedVendors")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Geotech")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GradingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GravelRingDimensionFt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Grounding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HorizCurveMinRadiusFt")
                        .HasColumnType("int");

                    b.Property<string>("Hydrology")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Innerduct")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InnerductPreloadedWithFiber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InterconnectAgreement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("InterconnectVoltageKv")
                        .HasColumnType("int");

                    b.Property<string>("LandControl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Layer1CompactionMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Layer1ScreenSizeIn")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Layer1ScreeningMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Layer2CompactionMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Layer2ScreenSizeIn")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Layer2ScreeningMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LowWaterCrossings")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MarkerBalls")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxLiftIn")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLoadingAt90cAmp")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxLongitudinalGradientPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("MaxMvCableSizeMcm")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSegmentLengthWithTailsFt")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTurbinesPerFeeder")
                        .HasColumnType("int");

                    b.Property<string>("MidSpanGrounding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MinPipeDiameterIn")
                        .HasColumnType("int");

                    b.Property<string>("MvCableApprovedVendors")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MvCableConductor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MvCableConductorShield")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MvCableEmergencyTempC")
                        .HasColumnType("int");

                    b.Property<string>("MvCableInsulation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MvCableInsulationShield")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MvCableJacket")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MvCableMaxContTempC")
                        .HasColumnType("int");

                    b.Property<string>("MvCableMetallicShield")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MvCableOrientation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MvCableVoltageKv")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MvConductorScWithstandKa")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MwacMw")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("NativeRho")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("NumberOfTurbines")
                        .HasColumnType("int");

                    b.Property<string>("OpportunityId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerSuppliedEquipment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermRoadXsection")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ppa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicRoadNetworkHaulRoute")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RunDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SingleModeFiber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceLocation")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("StandardTempRadiusFt")
                        .HasColumnType("int");

                    b.Property<string>("SubstationLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TailLengthOneSideFt")
                        .HasColumnType("int");

                    b.Property<string>("TempRoadXsection")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemporaryIntersections")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TerrainIssues")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TopoSurveySurfaceLidar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TopsoilOrganicDepthIn")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionRoute")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrenchBackfillLayer1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrenchBackfillLayer2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrenchBedding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TrenchCompactionPctStdProctor")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("TrenchDepthFt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TrenchDepthToTopOfCablesFt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TrenchGroundScWithstandKa")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrenchInstallationMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TrenchWidthFt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TurbineCenterpinOffsetFt")
                        .HasColumnType("int");

                    b.Property<int?>("TurbineHubHeightFt")
                        .HasColumnType("int");

                    b.Property<string>("TurbineLocations")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TurbineModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TurbineMw")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TurbineOem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TurbineRotorDiameterM")
                        .HasColumnType("int");

                    b.Property<decimal?>("TurbineTempDisturbanceAc")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TurbineTopOfPadShape")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TurbineTopOfPadSizeFt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VerticalCurveRadiusFt")
                        .HasColumnType("int");

                    b.Property<string>("WetlandDelineation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WtgPadsEarthworkCy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWindBODData", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectWindData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expver")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<double>("U10")
                        .HasColumnType("float");

                    b.Property<double>("V10")
                        .HasColumnType("float");

                    b.Property<DateTime>("ValidTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWindData", "Precon");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectMetaData", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "ParentProject")
                        .WithMany()
                        .HasForeignKey("ParentProjectId");

                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectNormals", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectWindBODData", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreconIQAPI.Models.ProjectWindData", b =>
                {
                    b.HasOne("PreconIQAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
